### ISSUE TITLE
compile on windows failed

### ISSUE THREAD

**Issue by shadoxxhd** [spring/mingwlibs#3]
I followed the 'building spring from source' guide.
Error message:

../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTV
N5boost16exception_detail19error_info_injectorISt13runtime_errorEE[__ZTVN5boost1
6exception_detail19error_info_injectorISt13runtime_errorEE]' has different size
../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTV
N5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_erro
rEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13r
untime_errorEEEE]' has different size
../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTV
N5boost16exception_detail19error_info_injectorISt11logic_errorEE[__ZTVN5boost16e
xception_detail19error_info_injectorISt11logic_errorEE]' has different size
../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTV
N5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorE
EEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11log
ic_errorEEEE]' has different size
CMakeFiles\unitsync.dir/objects.a(FileFilter.cpp.obj): In function `ZNK5boost9re
_detail31cpp_regex_traits_implementationIcE18lookup_collatenameB5cxx11EPKcS4_':
G:/git/spring/mingwlibs/include/boost/regex/v4/cpp_regex_traits.hpp:636: undefin
ed reference to `boost::re_detail::lookup_default_collate_name(std::__cxx11::bas
ic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles\unitsync.dir/objects.a(FileFilter.cpp.obj): In function `ZN5boost9re_
detail18basic_regex_parserIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE4fail
ENS_15regex_constants10error_typeEiNSt7__cxx1112basic_stringIcSt11char_traitsIcE
SaIcEEEi':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_parser.hpp:220: undef
ined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<ch
ar, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constant
s::error_type, int)'
CMakeFiles\unitsync.dir/objects.a(FileFilter.cpp.obj): In function `ZN5boost9re_
detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE16fi
xup_recursionsEPNS0_14re_syntax_baseE':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:793: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:875: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
CMakeFiles\unitsync.dir/objects.a(FileFilter.cpp.obj): In function `ZN5boost9re_
detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE15cr
eate_startmapEPNS0_14re_syntax_baseEPhPjh':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:1144: und
efined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<
char, std::char_traits<char>, std::allocator<char> > const&, boost::regex_consta
nts::error_type, int)'
CMakeFiles\unitsync.dir/objects.a(FileFilter.cpp.obj): In function `ZN5boost9re_
detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE16cr
eate_startmapsEPNS0_14re_syntax_baseE':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:941: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [tools\unitsync\CMakeFiles\unitsync.dir\build.make:1647: un
itsync.dll] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:2541: tools/unitsync/CMakeFiles/units
ync.dir/all] Error 2

and (after 'waiting for unfinished jobs'):

../../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_
ZTVN5boost16exception_detail19error_info_injectorISt13runtime_errorEE[__ZTVN5boo
st16exception_detail19error_info_injectorISt13runtime_errorEE]' has different si
ze
../../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_
ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_e
rrorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt
13runtime_errorEEEE]' has different size
../../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_
ZTVN5boost16exception_detail19error_info_injectorISt11logic_errorEE[__ZTVN5boost
16exception_detail19error_info_injectorISt11logic_errorEE]' has different size
../../../mingwlibs/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_
ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_err
orEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11
logic_errorEEEE]' has different size
CMakeFiles\engine-legacy.dir/objects.a(OBJParser.cpp.obj): In function `ZNK5boos
t9re_detail31cpp_regex_traits_implementationIcE18lookup_collatenameB5cxx11EPKcS4
_':
G:/git/spring/mingwlibs/include/boost/regex/v4/cpp_regex_traits.hpp:636: undefin
ed reference to `boost::re_detail::lookup_default_collate_name(std::__cxx11::bas
ic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles\engine-legacy.dir/objects.a(OBJParser.cpp.obj): In function `ZN5boost
9re_detail18basic_regex_parserIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE4
failENS_15regex_constants10error_typeEiNSt7__cxx1112basic_stringIcSt11char_trait
sIcESaIcEEEi':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_parser.hpp:220: undef
ined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<ch
ar, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constant
s::error_type, int)'
CMakeFiles\engine-legacy.dir/objects.a(OBJParser.cpp.obj): In function `ZN5boost
9re_detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE
16fixup_recursionsEPNS0_14re_syntax_baseE':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:793: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:875: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
CMakeFiles\engine-legacy.dir/objects.a(OBJParser.cpp.obj): In function `ZN5boost
9re_detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE
15create_startmapEPNS0_14re_syntax_baseEPhPjh':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:1144: und
efined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<
char, std::char_traits<char>, std::allocator<char> > const&, boost::regex_consta
nts::error_type, int)'
CMakeFiles\engine-legacy.dir/objects.a(OBJParser.cpp.obj): In function `ZN5boost
9re_detail19basic_regex_creatorIcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE
16create_startmapsEPNS0_14re_syntax_baseE':
G:/git/spring/mingwlibs/include/boost/regex/v4/basic_regex_creator.hpp:941: unde
fined reference to `boost::regex_error::regex_error(std::__cxx11::basic_string<c
har, std::char_traits<char>, std::allocator<char> > const&, boost::regex_constan
ts::error_type, int)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [rts\builds\legacy\CMakeFiles\engine-legacy.dir\build.make:
10636: spring.exe] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:4226: rts/builds/legacy/CMakeFiles/en
gine-legacy.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:4127: rts/builds/CMakeFiles/install-s
pring.dir/rule] Error 2
mingw32-make: *** [Makefile:1134: install-spring] Error 2

**Comment by abma** [comment]
should be fixed. current spring develop / maintenance can be compiled without boost!
